services:
  db:
    image: ankane/pgvector
    container_name: rag_pgvector
    restart: always
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    container_name: rag_streamlit
    ports:
      - "8501:8501"
    environment:
      # Database Configuration
      DB_CONN: postgresql://rag_user:rag_pass@db:5432/rag_db
      DATABASE_URL: postgresql://rag_user:rag_pass@db:5432/rag_db
      
      # White Label Configuration - Override these for each client
      APP_NAME: ${APP_NAME:-Raggy Muffin}
      APP_ICON: ${APP_ICON:-🧠}
      APP_TAGLINE: ${APP_TAGLINE:-Turn Your Documents Into Intelligent Conversations}
      APP_DESCRIPTION: ${APP_DESCRIPTION:-Built by researchers, for researchers. Upload your documents, ask questions in natural language, and get instant, accurate answers with source citations.}
      
      # Pricing Configuration
      STARTER_PLAN_PRICE: ${STARTER_PLAN_PRICE:-$19}
      STARTER_PLAN_PERIOD: ${STARTER_PLAN_PERIOD:-month}
      FREE_TRIAL_DAYS: ${FREE_TRIAL_DAYS:-14}
      STARTER_PLAN_PAGES: ${STARTER_PLAN_PAGES:-1,000}
      
      # Color Theme
      PRIMARY_COLOR: ${PRIMARY_COLOR:-#0066cc}
      SECONDARY_COLOR: ${SECONDARY_COLOR:-#666666}
      ACCENT_COLOR: ${ACCENT_COLOR:-#f9f9f9}
      
      # Company Information
      COMPANY_NAME: ${COMPANY_NAME:-Raggy Muffin Inc.}
      SUPPORT_EMAIL: ${SUPPORT_EMAIL:-support@raggymuffin.com}
      WEBSITE_URL: ${WEBSITE_URL:-https://raggymuffin.com}
      
      # AWS Cognito Configuration - REQUIRED for each deployment
      AWS_COGNITO_USER_POOL_ID: ${AWS_COGNITO_USER_POOL_ID}
      AWS_COGNITO_CLIENT_ID: ${AWS_COGNITO_CLIENT_ID}
      AWS_COGNITO_CLIENT_SECRET: ${AWS_COGNITO_CLIENT_SECRET}
      AWS_REGION: ${AWS_REGION:-us-east-1}
      
      # Features (pipe-separated)
      FEATURE_1_TITLE: ${FEATURE_1_TITLE:-Instant Insights}
      FEATURE_1_ICON: ${FEATURE_1_ICON:-🎯}
      FEATURE_1_DESC: ${FEATURE_1_DESC:-Upload documents and start asking questions immediately. No complex setup or training required.}
      FEATURE_1_QUOTE: ${FEATURE_1_QUOTE:-I can now analyze 100+ research papers in minutes instead of days}
      
      FEATURE_2_TITLE: ${FEATURE_2_TITLE:-Your Data, Your Control}
      FEATURE_2_ICON: ${FEATURE_2_ICON:-🔒}
      FEATURE_2_DESC: ${FEATURE_2_DESC:-Enterprise-grade security with complete data privacy. Your documents never leave your secure workspace.}
      FEATURE_2_QUOTE: ${FEATURE_2_QUOTE:-Finally, a solution that respects our confidential research data}
      
      FEATURE_3_TITLE: ${FEATURE_3_TITLE:-Pay Only For What You Use}
      FEATURE_3_ICON: ${FEATURE_3_ICON:-💰}
      FEATURE_3_DESC: ${FEATURE_3_DESC:-Transparent pricing based on document processing. No hidden fees, no surprises.}
      FEATURE_3_QUOTE: ${FEATURE_3_QUOTE:-More cost-effective than hiring a research assistant}
      
      # Testimonials
      TESTIMONIAL_1_TEXT: ${TESTIMONIAL_1_TEXT:-Raggy Muffin transformed how I conduct literature reviews. What used to take weeks now takes hours. The accuracy of answers and proper citations save me countless hours of verification.}
      TESTIMONIAL_1_AUTHOR: ${TESTIMONIAL_1_AUTHOR:-Dr. Sarah Chen}
      TESTIMONIAL_1_TITLE: ${TESTIMONIAL_1_TITLE:-Research Scientist, MIT}
      
      TESTIMONIAL_2_TEXT: ${TESTIMONIAL_2_TEXT:-As a legal researcher, I need precise information fast. Raggy Muffin helps me find relevant precedents and extract key arguments from hundreds of case documents effortlessly.}
      TESTIMONIAL_2_AUTHOR: ${TESTIMONIAL_2_AUTHOR:-Marcus Rodriguez}
      TESTIMONIAL_2_TITLE: ${TESTIMONIAL_2_TITLE:-Senior Legal Analyst}
      
      # Social Proof
      SOCIAL_PROOF_TEXT: ${SOCIAL_PROOF_TEXT:-Trusted by thousands of researchers, analysts, and knowledge workers worldwide}
      
      # CTA Configuration
      CTA_PRIMARY_TEXT: ${CTA_PRIMARY_TEXT:-GET STARTED FREE}
      CTA_SECONDARY_TEXT: ${CTA_SECONDARY_TEXT:-START FREE TRIAL}
      CTA_TRIAL_TEXT: ${CTA_TRIAL_TEXT:-Start your 14-day free trial}
      
      # Streamlit Configuration
      STREAMLIT_PAGE_TITLE: ${STREAMLIT_PAGE_TITLE:-Raggy Muffin - RAG Q&A Platform}
      STREAMLIT_PAGE_ICON: ${STREAMLIT_PAGE_ICON:-🧠}
      STREAMLIT_LAYOUT: ${STREAMLIT_LAYOUT:-wide}
    depends_on:
      - db
    volumes:
      - ./app:/app

volumes:
  pgdata:
